spring:
    profiles:
        active: prod
    application:
        name: Sonify
    mvc:
        format:
            date: yyyy-MM-dd
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 8080

logging:
    level:
        root: INFO
        com.citronix: DEBUG
        org.springframework.security: DEBUG
        com.Cataloger: DEBUG
        org.springframework.jdbc.core: TRACE
        org.springframework.web: DEBUG
 
   